{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/youtubepartner-content-owner-readonly": {
          "description": "View content owner account details from YouTube."
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://www.googleapis.com/",
  "batchPath": "batch/youtubePartner/v1",
  "canonicalName": "YouTube Partner",
  "description": "The YouTube Content ID API allows the management of YouTube assets along with their associated content, references, ownership, rights and policies.",
  "discoveryVersion": "v1",
  "documentationLink": "https://devsite.googleplex.com/youtube/partner/docs/v1/",
  "id": "youtubePartner:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "name": "youtubePartner",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "assetLabels": {
      "methods": {
        "insert": {
          "description": "Insert an asset label for an owner.",
          "flatPath": "youtube/partner/v1/assetLabels",
          "httpMethod": "POST",
          "id": "youtubePartner.assetLabels.insert",
          "path": "youtube/partner/v1/assetLabels",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of all asset labels for an owner.",
          "flatPath": "youtube/partner/v1/assetLabels",
          "httpMethod": "GET",
          "id": "youtubePartner.assetLabels.list",
          "path": "youtube/partner/v1/assetLabels",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "assetMatchPolicy": {
      "methods": {
        "get": {
          "description": "Retrieves the match policy assigned to the specified asset by the content owner associated with the authenticated user. This information is only accessible to an owner of the asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "httpMethod": "GET",
          "id": "youtubePartner.assetMatchPolicy.get",
          "path": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches the asset's match policy. If an asset has multiple owners, each owner may set its own match policy for the asset. YouTube then computes the match policy that is actually applied for the asset based on the territories where each owner owns the asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "httpMethod": "PATCH",
          "id": "youtubePartner.assetMatchPolicy.patch",
          "path": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates the asset's match policy. If an asset has multiple owners, each owner may set its own match policy for the asset. YouTube then computes the match policy that is actually applied for the asset based on the territories where each owner owns the asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "httpMethod": "PUT",
          "id": "youtubePartner.assetMatchPolicy.update",
          "path": "youtube/partner/v1/assets/{assetId}/matchPolicy",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "assetRelationships": {
      "methods": {
        "delete": {
          "description": "Deletes a relationship between two assets.",
          "flatPath": "youtube/partner/v1/assetRelationships/{assetRelationshipId}",
          "httpMethod": "DELETE",
          "id": "youtubePartner.assetRelationships.delete",
          "path": "youtube/partner/v1/assetRelationships/{assetRelationshipId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a relationship that links two assets.",
          "flatPath": "youtube/partner/v1/assetRelationships",
          "httpMethod": "POST",
          "id": "youtubePartner.assetRelationships.insert",
          "path": "youtube/partner/v1/assetRelationships",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of relationships for a given asset. The list contains relationships where the specified asset is either the parent (embedding) or child (embedded) asset in the relationship.",
          "flatPath": "youtube/partner/v1/assetRelationships",
          "httpMethod": "GET",
          "id": "youtubePartner.assetRelationships.list",
          "path": "youtube/partner/v1/assetRelationships",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "assetSearch": {
      "methods": {
        "list": {
          "description": "Searches for assets based on asset metadata. The method can retrieve all assets or only assets owned by the content owner. This method mimics the functionality of the advanced search feature on the Assets page in CMS.",
          "flatPath": "youtube/partner/v1/assetSearch",
          "httpMethod": "GET",
          "id": "youtubePartner.assetSearch.list",
          "path": "youtube/partner/v1/assetSearch",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "assetShares": {
      "methods": {
        "list": {
          "description": "This method either retrieves a list of asset shares the partner owns and that map to a specified asset view ID *or* it retrieves a list of asset views associated with a specified asset share ID owned by the partner.",
          "flatPath": "youtube/partner/v1/assetShares",
          "httpMethod": "GET",
          "id": "youtubePartner.assetShares.list",
          "path": "youtube/partner/v1/assetShares",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "assets": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata for the specified asset. Note that if the request identifies an asset that has been merged with another asset, meaning that YouTube identified the requested asset as a duplicate, then the request retrieves the merged, or synthesized, asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}",
          "httpMethod": "GET",
          "id": "youtubePartner.assets.get",
          "path": "youtube/partner/v1/assets/{assetId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Inserts an asset with the specified metadata. After inserting an asset, you can set its ownership data and match policy.",
          "flatPath": "youtube/partner/v1/assets",
          "httpMethod": "POST",
          "id": "youtubePartner.assets.insert",
          "path": "youtube/partner/v1/assets",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of assets based on asset metadata. The method can retrieve all assets or only assets owned by the content owner. Note that in cases where duplicate assets have been merged, the API response only contains the synthesized asset. (It does not contain the constituent assets that were merged into the synthesized asset.)",
          "flatPath": "youtube/partner/v1/assets",
          "httpMethod": "GET",
          "id": "youtubePartner.assets.list",
          "path": "youtube/partner/v1/assets",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches the metadata for the specified asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.assets.patch",
          "path": "youtube/partner/v1/assets/{assetId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates the metadata for the specified asset.",
          "flatPath": "youtube/partner/v1/assets/{assetId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.assets.update",
          "path": "youtube/partner/v1/assets/{assetId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "campaigns": {
      "methods": {
        "delete": {
          "description": "Deletes a specified campaign for an owner.",
          "flatPath": "youtube/partner/v1/campaigns/{campaignId}",
          "httpMethod": "DELETE",
          "id": "youtubePartner.campaigns.delete",
          "path": "youtube/partner/v1/campaigns/{campaignId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "get": {
          "description": "Retrieves a particular campaign for an owner.",
          "flatPath": "youtube/partner/v1/campaigns/{campaignId}",
          "httpMethod": "GET",
          "id": "youtubePartner.campaigns.get",
          "path": "youtube/partner/v1/campaigns/{campaignId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Insert a new campaign for an owner using the specified campaign data.",
          "flatPath": "youtube/partner/v1/campaigns",
          "httpMethod": "POST",
          "id": "youtubePartner.campaigns.insert",
          "path": "youtube/partner/v1/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of campaigns for an owner.",
          "flatPath": "youtube/partner/v1/campaigns",
          "httpMethod": "GET",
          "id": "youtubePartner.campaigns.list",
          "path": "youtube/partner/v1/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patch the data for a specific campaign.",
          "flatPath": "youtube/partner/v1/campaigns/{campaignId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.campaigns.patch",
          "path": "youtube/partner/v1/campaigns/{campaignId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Update the data for a specific campaign.",
          "flatPath": "youtube/partner/v1/campaigns/{campaignId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.campaigns.update",
          "path": "youtube/partner/v1/campaigns/{campaignId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "claimHistory": {
      "methods": {
        "get": {
          "description": "Retrieves the claim history for a specified claim.",
          "flatPath": "youtube/partner/v1/claimHistory/{claimId}",
          "httpMethod": "GET",
          "id": "youtubePartner.claimHistory.get",
          "path": "youtube/partner/v1/claimHistory/{claimId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "claimSearch": {
      "methods": {
        "list": {
          "description": "Retrieves a list of claims that match the search criteria. You can search for claims that are associated with a specific asset or video or that match a specified query string.",
          "flatPath": "youtube/partner/v1/claimSearch",
          "httpMethod": "GET",
          "id": "youtubePartner.claimSearch.list",
          "path": "youtube/partner/v1/claimSearch",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "claims": {
      "methods": {
        "get": {
          "description": "Retrieves a specific claim by ID.",
          "flatPath": "youtube/partner/v1/claims/{claimId}",
          "httpMethod": "GET",
          "id": "youtubePartner.claims.get",
          "path": "youtube/partner/v1/claims/{claimId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a claim. The video being claimed must have been uploaded to a channel associated with the same content owner as the API user sending the request. You can set the claim's policy in any of the following ways: - Use the claim resource's policy property to identify a saved policy by its unique ID. - Use the claim resource's policy property to specify a custom set of rules. ",
          "flatPath": "youtube/partner/v1/claims",
          "httpMethod": "POST",
          "id": "youtubePartner.claims.insert",
          "path": "youtube/partner/v1/claims",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of claims administered by the content owner associated with the currently authenticated user. Results are sorted in descending order of creation time.",
          "flatPath": "youtube/partner/v1/claims",
          "httpMethod": "GET",
          "id": "youtubePartner.claims.list",
          "path": "youtube/partner/v1/claims",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches an existing claim by either changing its policy or its status. You can update a claim's status from active to inactive to effectively release the claim.",
          "flatPath": "youtube/partner/v1/claims/{claimId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.claims.patch",
          "path": "youtube/partner/v1/claims/{claimId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates an existing claim by either changing its policy or its status. You can update a claim's status from active to inactive to effectively release the claim.",
          "flatPath": "youtube/partner/v1/claims/{claimId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.claims.update",
          "path": "youtube/partner/v1/claims/{claimId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "contentOwners": {
      "methods": {
        "get": {
          "description": "Retrieves information about the specified content owner.",
          "flatPath": "youtube/partner/v1/contentOwners/{contentOwnerId}",
          "httpMethod": "GET",
          "id": "youtubePartner.contentOwners.get",
          "path": "youtube/partner/v1/contentOwners/{contentOwnerId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of content owners that match the request criteria.",
          "flatPath": "youtube/partner/v1/contentOwners",
          "httpMethod": "GET",
          "id": "youtubePartner.contentOwners.list",
          "path": "youtube/partner/v1/contentOwners",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/youtubepartner-content-owner-readonly"
          ]
        }
      }
    },
    "liveCuepoints": {
      "methods": {
        "insert": {
          "description": "Inserts a cuepoint into a live broadcast.",
          "flatPath": "youtube/partner/v1/liveCuepoints",
          "httpMethod": "POST",
          "id": "youtubePartner.liveCuepoints.insert",
          "path": "youtube/partner/v1/liveCuepoints",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "metadataHistory": {
      "methods": {
        "list": {
          "description": "Retrieves a list of all metadata provided for an asset, regardless of which content owner provided the data.",
          "flatPath": "youtube/partner/v1/metadataHistory",
          "httpMethod": "GET",
          "id": "youtubePartner.metadataHistory.list",
          "path": "youtube/partner/v1/metadataHistory",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "ownership": {
      "methods": {
        "get": {
          "description": "Retrieves the ownership data provided for the specified asset by the content owner associated with the authenticated user.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/ownership",
          "httpMethod": "GET",
          "id": "youtubePartner.ownership.get",
          "path": "youtube/partner/v1/assets/{assetId}/ownership",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Provides new ownership information for the specified asset. Note that YouTube may receive ownership information from multiple sources. For example, if an asset has multiple owners, each owner might send ownership data for the asset. YouTube algorithmically combines the ownership data received from all of those sources to generate the asset's canonical ownership data, which should provide the most comprehensive and accurate representation of the asset's ownership.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/ownership",
          "httpMethod": "PATCH",
          "id": "youtubePartner.ownership.patch",
          "path": "youtube/partner/v1/assets/{assetId}/ownership",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Provides new ownership information for the specified asset. Note that YouTube may receive ownership information from multiple sources. For example, if an asset has multiple owners, each owner might send ownership data for the asset. YouTube algorithmically combines the ownership data received from all of those sources to generate the asset's canonical ownership data, which should provide the most comprehensive and accurate representation of the asset's ownership.",
          "flatPath": "youtube/partner/v1/assets/{assetId}/ownership",
          "httpMethod": "PUT",
          "id": "youtubePartner.ownership.update",
          "path": "youtube/partner/v1/assets/{assetId}/ownership",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "ownershipHistory": {
      "methods": {
        "list": {
          "description": "Retrieves a list of the ownership data for an asset, regardless of which content owner provided the data. The list only includes the most recent ownership data for each content owner. However, if the content owner has submitted ownership data through multiple data sources (API, content feeds, etc.), the list will contain the most recent data for each content owner and data source.",
          "flatPath": "youtube/partner/v1/ownershipHistory",
          "httpMethod": "GET",
          "id": "youtubePartner.ownershipHistory.list",
          "path": "youtube/partner/v1/ownershipHistory",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "package": {
      "methods": {
        "get": {
          "description": "Retrieves information for the specified package.",
          "flatPath": "youtube/partner/v1/package/{packageId}",
          "httpMethod": "GET",
          "id": "youtubePartner.package.get",
          "path": "youtube/partner/v1/package/{packageId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Inserts a metadata-only package.",
          "flatPath": "youtube/partner/v1/package",
          "httpMethod": "POST",
          "id": "youtubePartner.package.insert",
          "path": "youtube/partner/v1/package",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "policies": {
      "methods": {
        "get": {
          "description": "Retrieves the specified saved policy.",
          "flatPath": "youtube/partner/v1/policies/{policyId}",
          "httpMethod": "GET",
          "id": "youtubePartner.policies.get",
          "path": "youtube/partner/v1/policies/{policyId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a saved policy.",
          "flatPath": "youtube/partner/v1/policies",
          "httpMethod": "POST",
          "id": "youtubePartner.policies.insert",
          "path": "youtube/partner/v1/policies",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of the content owner's saved policies.",
          "flatPath": "youtube/partner/v1/policies",
          "httpMethod": "GET",
          "id": "youtubePartner.policies.list",
          "path": "youtube/partner/v1/policies",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches the specified saved policy.",
          "flatPath": "youtube/partner/v1/policies/{policyId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.policies.patch",
          "path": "youtube/partner/v1/policies/{policyId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates the specified saved policy.",
          "flatPath": "youtube/partner/v1/policies/{policyId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.policies.update",
          "path": "youtube/partner/v1/policies/{policyId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "referenceConflicts": {
      "methods": {
        "get": {
          "description": "Retrieves information about the specified reference conflict.",
          "flatPath": "youtube/partner/v1/referenceConflicts/{referenceConflictId}",
          "httpMethod": "GET",
          "id": "youtubePartner.referenceConflicts.get",
          "path": "youtube/partner/v1/referenceConflicts/{referenceConflictId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of unresolved reference conflicts.",
          "flatPath": "youtube/partner/v1/referenceConflicts",
          "httpMethod": "GET",
          "id": "youtubePartner.referenceConflicts.list",
          "path": "youtube/partner/v1/referenceConflicts",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "references": {
      "methods": {
        "get": {
          "description": "Retrieves information about the specified reference.",
          "flatPath": "youtube/partner/v1/references/{referenceId}",
          "httpMethod": "GET",
          "id": "youtubePartner.references.get",
          "path": "youtube/partner/v1/references/{referenceId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Creates a reference in one of the following ways: - If your request is uploading a reference file, YouTube creates the reference from the provided content. You can provide either a video/audio file or a pre-generated fingerprint. If you are providing a pre-generated fingerprint, set the reference resource's fpDirect property to true in the request body. In this flow, you can use either the multipart or resumable upload flows to provide the reference content. - If you wa[...]",
          "flatPath": "youtube/partner/v1/references",
          "httpMethod": "POST",
          "id": "youtubePartner.references.insert",
          "path": "youtube/partner/v1/references",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true
        },
        "list": {
          "description": "Retrieves a list of references by ID or the list of references for the specified asset.",
          "flatPath": "youtube/partner/v1/references",
          "httpMethod": "GET",
          "id": "youtubePartner.references.list",
          "path": "youtube/partner/v1/references",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches a reference.",
          "flatPath": "youtube/partner/v1/references/{referenceId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.references.patch",
          "path": "youtube/partner/v1/references/{referenceId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates a reference.",
          "flatPath": "youtube/partner/v1/references/{referenceId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.references.update",
          "path": "youtube/partner/v1/references/{referenceId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "spreadsheetTemplate": {
      "methods": {
        "list": {
          "description": "Retrieves a list of spreadsheet templates for a content owner.",
          "flatPath": "youtube/partner/v1/spreadsheetTemplate",
          "httpMethod": "GET",
          "id": "youtubePartner.spreadsheetTemplate.list",
          "path": "youtube/partner/v1/spreadsheetTemplate",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "uploader": {
      "methods": {
        "list": {
          "description": "Retrieves a list of uploaders for a content owner.",
          "flatPath": "youtube/partner/v1/uploader",
          "httpMethod": "GET",
          "id": "youtubePartner.uploader.list",
          "path": "youtube/partner/v1/uploader",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "validator": {
      "methods": {
        "validate": {
          "description": "Validate a metadata file.",
          "flatPath": "youtube/partner/v1/validator",
          "httpMethod": "POST",
          "id": "youtubePartner.validator.validate",
          "path": "youtube/partner/v1/validator",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "validateAsync": {
          "description": "Validate a metadata file asynchronously.",
          "flatPath": "youtube/partner/v1/validatorAsync",
          "httpMethod": "POST",
          "id": "youtubePartner.validator.validateAsync",
          "path": "youtube/partner/v1/validatorAsync",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "validateAsyncStatus": {
          "description": "Get the asynchronous validation status.",
          "flatPath": "youtube/partner/v1/validatorAsyncStatus",
          "httpMethod": "POST",
          "id": "youtubePartner.validator.validateAsyncStatus",
          "path": "youtube/partner/v1/validatorAsyncStatus",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "videoAdvertisingOptions": {
      "methods": {
        "get": {
          "description": "Retrieves advertising settings for the specified video.",
          "flatPath": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "httpMethod": "GET",
          "id": "youtubePartner.videoAdvertisingOptions.get",
          "path": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "getEnabledAds": {
          "description": "Retrieves details about the types of allowed ads for a specified partner- or user-uploaded video.",
          "flatPath": "youtube/partner/v1/videoAdvertisingOptions/{videoId}/getEnabledAds",
          "httpMethod": "GET",
          "id": "youtubePartner.videoAdvertisingOptions.getEnabledAds",
          "path": "youtube/partner/v1/videoAdvertisingOptions/{videoId}/getEnabledAds",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "patch": {
          "description": "Patches the advertising settings for the specified video.",
          "flatPath": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "httpMethod": "PATCH",
          "id": "youtubePartner.videoAdvertisingOptions.patch",
          "path": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "description": "Updates the advertising settings for the specified video.",
          "flatPath": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "httpMethod": "PUT",
          "id": "youtubePartner.videoAdvertisingOptions.update",
          "path": "youtube/partner/v1/videoAdvertisingOptions/{videoId}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "whitelists": {
      "methods": {
        "delete": {
          "description": "Removes a whitelisted channel for a content owner.",
          "flatPath": "youtube/partner/v1/whitelists/{id}",
          "httpMethod": "DELETE",
          "id": "youtubePartner.whitelists.delete",
          "path": "youtube/partner/v1/whitelists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "get": {
          "description": "Retrieves a specific whitelisted channel by ID.",
          "flatPath": "youtube/partner/v1/whitelists/{id}",
          "httpMethod": "GET",
          "id": "youtubePartner.whitelists.get",
          "path": "youtube/partner/v1/whitelists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "description": "Whitelist a YouTube channel for your content owner. Whitelisted channels are channels that are not owned or managed by you, but you would like to whitelist so that no claims from your assets are placed on videos uploaded to these channels.",
          "flatPath": "youtube/partner/v1/whitelists",
          "httpMethod": "POST",
          "id": "youtubePartner.whitelists.insert",
          "path": "youtube/partner/v1/whitelists",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "description": "Retrieves a list of whitelisted channels for a content owner.",
          "flatPath": "youtube/partner/v1/whitelists",
          "httpMethod": "GET",
          "id": "youtubePartner.whitelists.list",
          "path": "youtube/partner/v1/whitelists",
          "scopes": [
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    }
  },
  "revision": "20211221",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "",
  "title": "YouTube Content ID API",
  "version": "v1",
  "version_module": true
}